-- =============================================================
-- Migration: fix audit hash-chain false-positive breaks
-- =============================================================
-- Background
-- ----------
-- inventory_transactions is an append-only audit log protected by a
-- sha256 hash chain (each row stores prev_hash = the previous row's
-- row_hash). A nightly cron (audit-chain-verify) walks the chain and
-- raises an 'audit_chain_alert' row if a link doesn't match.
--
-- Since ~2026-05-30 the verifier has alerted every night. Investigation
-- (2026-06-01) showed this is a FALSE POSITIVE, not tampering:
--
--   * 13,793 rows, 0 orphaned prev_hash values, 0 duplicate row_hashes
--     => no row was deleted, altered, or lost. Data integrity is intact.
--   * 8,215 rows share an exact created_at timestamp with another row,
--     because high-volume writers (the ShipStation apply RPC) insert
--     several rows in one transaction and Postgres stamps them all with
--     the same now().
--
-- Root cause: the INSERT trigger picked the chain tip with
--   ORDER BY created_at DESC, id DESC LIMIT 1
-- and the verifier walked the chain with
--   ORDER BY created_at ASC, id ASC.
-- When two rows share created_at, the id tie-break does NOT match the
-- real insertion order. The trigger then chains a new row onto whichever
-- sibling has the larger id rather than the one actually inserted last,
-- producing a *fork*: two rows point at the same parent and one sibling
-- becomes a dead-end branch. The verifier, walking by (created_at, id),
-- hits the dead-end branch and reports "prev_hash mismatch".
--
-- Fix (forward-only, no history rewrite)
-- --------------------------------------
--   1. Add a monotonic `seq` identity column. Identity values are handed
--      out in true insertion order and never tie, giving a single total
--      order that both the trigger and the verifier can agree on.
--   2. Trigger: take a transaction-level advisory lock (serialize audit
--      inserts so concurrent transactions can't both read the same tip)
--      and pick the tip with ORDER BY seq DESC. New rows now form a
--      strictly linear chain.
--   3. Verifier: walk by seq ASC and verify each prev_hash link +
--      recompute each row_hash.
--   4. Checkpoint: record the current max(seq) in audit_chain_config.
--      The verifier defaults to checking only rows AFTER the checkpoint.
--      The pre-fix forked history is sealed off and trusted as-is (it is
--      provably complete: 0 orphans, 0 dup hashes) rather than having all
--      13,793 historical hashes rewritten on prod. Tamper-evidence is
--      fully active from the checkpoint forward.
--   5. Repoint the audit-chain-verify cron at the new no-arg verifier.
--
-- A full historical re-verification can be run any time for forensics via
--   SELECT * FROM verify_audit_chain(0);   -- 0 = scan from genesis
-- (expected to report the first historical fork; that's the known,
-- documented pre-fix structure, not new tampering).
-- =============================================================

-- -------------------------------------------------------------
-- 1. Monotonic sequence column (true insertion order, no ties)
-- -------------------------------------------------------------
-- ADD COLUMN with an identity default backfills existing rows via an
-- internal table rewrite, not a row-level UPDATE, so the immutability
-- block trigger (BEFORE UPDATE/DELETE) does not fire. Append-only table
-- => the backfill order tracks physical/insertion order, but historical
-- seq precision is irrelevant: the verifier only walks post-checkpoint
-- rows, and those get their seq from new inserts.
ALTER TABLE public.inventory_transactions
  ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Unique index: speeds the trigger's tip lookup (ORDER BY seq DESC LIMIT 1)
-- and the verifier's range scan (WHERE seq > checkpoint ORDER BY seq ASC).
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_tx_seq
  ON public.inventory_transactions (seq);

-- -------------------------------------------------------------
-- 2. Checkpoint config (the trust boundary)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_chain_config (
  id              INTEGER PRIMARY KEY DEFAULT 1,
  checkpoint_seq  BIGINT  NOT NULL,
  set_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT audit_chain_config_singleton CHECK (id = 1)
);

-- Seal the pre-fix history: verification starts after the current tip.
INSERT INTO public.audit_chain_config (id, checkpoint_seq)
VALUES (1, COALESCE((SELECT MAX(seq) FROM public.inventory_transactions), 0))
ON CONFLICT (id) DO UPDATE
  SET checkpoint_seq = EXCLUDED.checkpoint_seq,
      set_at = now();

-- Lock the config down: readable by the verifier (runs as table owner /
-- service_role, which bypass RLS), not writable by app users.
ALTER TABLE public.audit_chain_config ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- 3. Trigger: serialize + chain by seq
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.audit_hash_chain()
RETURNS TRIGGER AS $$
DECLARE
  v_prev_hash TEXT;
  v_payload   TEXT;
BEGIN
  -- Serialize audit-chain inserts. Without this, two concurrent
  -- transactions can each read the same tip before either commits and
  -- both chain onto it (a fork). A transaction-level advisory lock makes
  -- chain extension single-file; it auto-releases at COMMIT/ROLLBACK.
  -- The key is an arbitrary constant unique to this chain.
  PERFORM pg_advisory_xact_lock(74010983);

  -- Current chain tip, by the monotonic seq (insertion order, no ties).
  SELECT row_hash INTO v_prev_hash
    FROM public.inventory_transactions
   ORDER BY seq DESC
   LIMIT 1;

  NEW.prev_hash := COALESCE(v_prev_hash, '0000000000000000000000000000000000000000000000000000000000000000');

  v_payload := COALESCE(NEW.id::text, '') || '|'
            || COALESCE(NEW.sku_id::text, '') || '|'
            || COALESCE(NEW.transaction_type, '') || '|'
            || COALESCE(NEW.quantity::text, '') || '|'
            || COALESCE(NEW.field_affected, '') || '|'
            || COALESCE(NEW.movement_kind, '') || '|'
            || COALESCE(NEW.from_field, '') || '|'
            || COALESCE(NEW.to_field, '') || '|'
            || COALESCE(NEW.reference_id::text, '') || '|'
            || COALESCE(NEW.reference_type, '') || '|'
            || COALESCE(NEW.notes, '') || '|'
            || COALESCE(NEW.performed_by::text, '') || '|'
            || COALESCE(NEW.created_at::text, now()::text) || '|'
            || NEW.prev_hash;

  NEW.row_hash := encode(digest(v_payload, 'sha256'), 'hex');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -------------------------------------------------------------
-- 4. Verifier: walk by seq from the checkpoint
-- -------------------------------------------------------------
-- Signature changes from (timestamptz) to (bigint), so drop the old one
-- first (CREATE OR REPLACE can't change argument types). The cron is
-- repointed at the new no-arg form in step 5.
DROP FUNCTION IF EXISTS public.verify_audit_chain(TIMESTAMPTZ);

CREATE OR REPLACE FUNCTION public.verify_audit_chain(p_from_seq BIGINT DEFAULT NULL)
RETURNS TABLE (first_broken_id UUID, first_broken_at TIMESTAMPTZ, message TEXT) AS $$
DECLARE
  r              RECORD;
  v_start_seq    BIGINT;
  v_expected_prev TEXT;
  v_recomputed   TEXT;
BEGIN
  -- NULL => use the stored checkpoint (default, what the cron calls).
  -- Pass 0 to force a full-history scan (forensics).
  v_start_seq := COALESCE(
    p_from_seq,
    (SELECT checkpoint_seq FROM public.audit_chain_config WHERE id = 1),
    0
  );

  -- Seed expected prev_hash with the row at the checkpoint (the last
  -- trusted row); genesis-zero if starting from the very beginning.
  SELECT row_hash INTO v_expected_prev
    FROM public.inventory_transactions
   WHERE seq = v_start_seq
   LIMIT 1;
  v_expected_prev := COALESCE(v_expected_prev,
    '0000000000000000000000000000000000000000000000000000000000000000');

  FOR r IN
    SELECT * FROM public.inventory_transactions
     WHERE seq > v_start_seq
     ORDER BY seq ASC
  LOOP
    IF r.prev_hash != v_expected_prev THEN
      RETURN QUERY SELECT r.id, r.created_at, format('prev_hash mismatch at row %s', r.id);
      RETURN;
    END IF;

    v_recomputed := encode(digest(
      COALESCE(r.id::text, '') || '|'
      || COALESCE(r.sku_id::text, '') || '|'
      || COALESCE(r.transaction_type, '') || '|'
      || COALESCE(r.quantity::text, '') || '|'
      || COALESCE(r.field_affected, '') || '|'
      || COALESCE(r.movement_kind, '') || '|'
      || COALESCE(r.from_field, '') || '|'
      || COALESCE(r.to_field, '') || '|'
      || COALESCE(r.reference_id::text, '') || '|'
      || COALESCE(r.reference_type, '') || '|'
      || COALESCE(r.notes, '') || '|'
      || COALESCE(r.performed_by::text, '') || '|'
      || COALESCE(r.created_at::text, '') || '|'
      || r.prev_hash,
      'sha256'
    ), 'hex');
    IF v_recomputed != r.row_hash THEN
      RETURN QUERY SELECT r.id, r.created_at, format('row_hash does not match recomputation at %s', r.id);
      RETURN;
    END IF;

    v_expected_prev := r.row_hash;
  END LOOP;

  -- Chain is intact
  RETURN;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.verify_audit_chain IS
  'Walks the audit hash chain by seq from the checkpoint (audit_chain_config) and returns the first broken row, or no rows if intact. Pass 0 to scan from genesis (forensics). Run nightly by the audit-chain-verify cron.';

-- -------------------------------------------------------------
-- 5. Repoint the cron at the new no-arg verifier
-- -------------------------------------------------------------
-- Unschedule only if present (cron.unschedule(name) throws when the job
-- doesn't exist, e.g. on an environment that never bootstrapped it).
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'audit-chain-verify';
SELECT cron.schedule(
  'audit-chain-verify',
  '30 4 * * *',
  $cron$
    INSERT INTO inventory_transactions (
      sku_id, transaction_type, quantity, field_affected,
      movement_kind, notes, performed_by
    )
    SELECT
      NULL, 'audit_chain_alert', 0, 'row_hash',
      'metadata',
      format('Chain broken starting at %s: %s', first_broken_id, message),
      '00000000-0000-0000-0000-000000000001'::uuid
    FROM verify_audit_chain()
    LIMIT 1;
  $cron$
);
